### ISSUE TITLE
UnboundLocalError: local variable 'model' referenced before assignment

### ISSUE THREAD

**Issue by bahhhhh** [WardsParadox/PrinterProfileGenerator#2] opened 2017-08-25 19:38 UTC
I'm using the latest version of `profile_generator.py` to create a config profile for a printer we recently purchased, but I've run into an issue. Some info:

- Printer model: HP Color LaserJet Professional CP5225n
- Driver: HP Color LaserJet CP5220 Series.gz

The command I'm using: `profile_generator.py --printername "printer_name" --driver "HP Color LaserJet CP5220 Series.gz" --address "smb://printer%20name" --location "office location" --displayname "HP Laserjet CP5225N" --version "0.1"  --organization "companyName"`

The error I'm getting:

```
Traceback (most recent call last):
  File "/Users/Master/bin/profile_generator.py", line 218, in <module>
    main()
  File "/Users/Master/bin/profile_generator.py", line 156, in main
    _printer["Model"] = model
UnboundLocalError: local variable 'model' referenced before assignment
```

Any idea what I'm doing wrong?

**Comment by WardsParadox** [comment] 2017-08-25 22:08
I found the issue, my test for a relative file location is not working as intended and I will be fixing it shortly. For now, please specify the full path to the driver.

**Comment by WardsParadox** [comment] 2017-08-25 22:12
And now it's working with the same command.. 🤔

**Comment by WardsParadox** [comment] 2017-08-25 22:15
It's something specific with that Driver and not having the line that it needs. Let me look into it some more.

**Comment by WardsParadox** [comment] 2017-08-25 22:22
That driver uses a tab on the `*NickName` field as opposed to most every other driver that uses a space. I just need to update my codes to get that info more reliably. Thanks for letting me know @bahhhhh, It should now be fixed in the latest release.

**Closed as completed** 2017-08-25 22:22 UTC
